### ISSUE TITLE
The create command is not visible in the menu

### ISSUE THREAD

**Issue by Morriz** [testpossessed/auto-barrel#12]
The create command is not visible anymore.

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by testpossessed** [comment]
I had a quick look and it the command is there for me when I right click on a folder, but I am running Windows at the moment.

I will boot into MacOS over the weekend and check there

**Comment by testpossessed** [comment]
I am in OsX Catalina and VS Code 1.44.2 and right clicking on any folder presents the Create Barrel option as expected.  Also right clicking on an index.ts file presents the Update Barrel option as expected.

If you could provide some screen shots that show the issue I can try looking into further.  For now all I can suggest is uninstalling and re-installing Auto Barrel and perhaps VS Code.
