### ISSUE TITLE
The create command is not working from the cmd prompt

### ISSUE THREAD

**Issue by Morriz** [testpossessed/auto-barrel#13]
I get these errors on a `.ts` file:

```
No editors associated with document: ...
```
```
(node:43985) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```
and
```
Command 'Create Barrel' resulted in an error (Running the contributed command: 'autoBarrel.createBarrel' failed.)
```

**Comment by testpossessed** [comment]
Create Barrel and Update Barrel are not supported from the command pallete as I was not able to find a way to identify the folder or file selected in the explorer.  I would have to prompt for the folder to create a barrel in or the file to update and I do not feel that is a good experience so I limited the commands to the explorer menu.

The should not appear in the command pallette, the don't in my environment. so I am guessing you are typing the whole command.

**Comment by Morriz** [comment]
Aha. But they did. Both commands appeared in my console.

**Comment by testpossessed** [comment]
Ok, back to checking over the weekend then once I can boot into Mac OS.  My work requires Windows at the moment and I prefer to do this via bootcamp rather than Parrallels.

**Comment by testpossessed** [comment]
I am booted into Osx Catalina with the latest v 1.44.2 of VS Code installed and Auto Barrel installed and enabled and when pressing CMD+Shift+P I only see the two expected commands Start and Stop.  So as far as I can see the commands are correctly contributed.

You mentioned they appear in your "console" rather than command pallette, how are you trying to run the command?
