### ISSUE TITLE
Support ignoring files

### ISSUE THREAD

**Issue by snebjorn** [testpossessed/auto-barrel#14]
Sometimes it's needed to not include certain files in a barrel, this can be due to cyclic imports.

I'd like to somehow be able to ignore files and folders. Preferably via glob pattern.
Not sure where the best place for the _config_ would be.

I see two options. Via a `.barrel` file or via comments inside index.ts. 
```
// auto-barrel-ignore ./subfolder/**
// auto-barrel-ignore ./somefile
export * from '.something';
```

There are pros and cons to both.

**Comment by testpossessed** [comment]
There is already a setting for Auto Barrel "Ignore File Path Containing Any Of", which can be set at workspace level, will this not achive what you want?

It defaults to .spec,.test but you could put a partial path something like parent/subfolder in and it will be ignored.  This puts the ignore right at the file system watcher level for auto barrelling so no need to check config files or individual barrel files

**Comment by snebjorn** [comment]
It almost solves it.

However I'm still interested in generating a barrel inside `./subfolder/` it should just not be included in the `.index.ts` barrel.

Adding `src/app/subfolder/` to the ignore file paths also stops the generation of `./subfolder/index.ts`

**Comment by testpossessed** [comment]
I experimented with some options and decided not to do anything about this as it opened up too many opportunities for defects and had a detremental effect on performance.

Whilst I accept people should be able to work how they want, I consider this an edge case scenario that I have never seen in my many years of contracting and would never implement myself so given the impact mentioned above during my limited research I made the decision no to support it.
