### ISSUE TITLE
Optional semicolon settings

### ISSUE THREAD

**Issue by fromcouch** [testpossessed/auto-barrel#18]
Working with typescript, the new ESLint rules, avoid using semicolons at the end of the line.

Do you have or plan to include any setting for add or not semicolons at the end of the lines?

Actually every time that barrel file is generated I need to go and remove all semicolons.

Thanks

**Comment by testpossessed** [comment]
I wasn't planning on it because I disagree quite strongly with that rule and disable it in every project.  But since it has effectively become a request I will upade the project in the next couple of days.

**Comment by fromcouch** [comment]
Really Thank, I totally disagree too, but someone added the last eslint airbnb rules to our typescript project and we are removing all semicolons in our project without apparent reason to avoid linter errors.

**Comment by testpossessed** [comment]
All done, v1.8.0 has been published and verified.
