### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by Kirpal** [testpossessed/auto-barrel#2]
I'm hoping to possibly create a fork of this extension for dart barrel files. However, I don't see a license anywhere that indicates if I could do that or not. Could you please add a license to this repository?

[Helpful resource](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license)

**Comment by testpossessed** [comment]
I have now separated the code into a private repository so closing this issue.
