### ISSUE TITLE
Stable ordering for imports

### ISSUE THREAD

**Issue by npbenjohnson** [testpossessed/auto-barrel#21]
Running recursive auto barrel generates a different ordering of imports when re-run with no changes, which makes a mess in source control.

**Comment by testpossessed** [comment]
I looked at this before when someone questioned it.  The project doesn't do any specific ordering, it loads the file using a workspace edit object from the VS Code API.  It then either appends a new line after the last one or removes an existing like.  The edit is then applied and it is the VS Code Api that actually handles the write.  I couldn't see any way to guarantee the ordering at the time, but will take another look in case there have been improvements in this area recently.

**Comment by testpossessed** [comment]
I can't find a way to guarantee the order without stepping outside of the responsibilities of the extension.  Happy to consider a PR if someone with more expertise with the API cares to jump it.  As long as it does not step outside of responsibilities for the extension e.g. Triggering auto format or something like that.
