### ISSUE TITLE
[Bug?] Option "Update Barrel" by adding yourself.

### ISSUE THREAD

**Issue by dziul** [testpossessed/auto-barrel#26]
version: 1.9.1

The generation of the Barrel file is perfect so far, but when I need to update using the "update barrel"... option the updated file is being added to itself.

example:

I have the `index.ts` file

```ts
export * from './types';
```

when I use the "update barrel" option:

```ts
export * from './types';
export * from './new-module';

export * from './index'; //yourself
```

so I need every update to remove that `export * from './index'`.

how to solve this? tried using `ignoreFilePathContainingAnyOf ="index.ts"`, but it ignores all `index.ts|x`

**Comment by testpossessed** [comment]
I cannot replicate this issue.  The code is definitely there in update-barrel to remove the barrel file and in debugging it I can see that this code is working to remove the barrel file itself from the list before updating the contents.  If you could provide some screen shots of your folder/file structure I might be able to get furthier.

**Comment by dziul** [comment]
hello, @testpossessed. I don't know if there was any update or something here. But this bug is not happening. I thank .
