### ISSUE TITLE
Track subfolders with command "Auto Barrel - Start"

### ISSUE THREAD

**Issue by labarilem** [testpossessed/auto-barrel#3]
Hi,
I've been using this extension for the last few days and I find it very useful. 😄 
Still, in my opinion, it could be improved by handling exports of subfolders too.

E.g.
With the command _AutoBarrel - Start_, the extension should also add export statements in a barrel file when a new subfolder with an _index.ts_ file is created in the folder containing the mentioned barrel file.

I guess this one might be a common use case.
Let me know what you think about this, I could look into it. 🤓

**Comment by testpossessed** [comment]
Hi,

Glad you like the tool and it is proving useful to you.

I agree, this is a feature I have been meaning to add since the beginning, but never found the time.  I have time today though so will try to get it done.

The main concern I have is that I use a single file system watcher when the Start command is activated.  This avoids impacting performance with separate watchers for each folder.  To maintain this approach would mean that users would need to explicitly exclude files index.* files that are not barrels either using the relevant setting or adding a comment.  Not too much of a hardship but perhaps an inconvenience and easy to forget.

**Comment by testpossessed** [comment]
I have just published and update that introduces this feature.  Have a look when you get a chance and let me know if there are any issues.

**Comment by labarilem** [comment]
I've tried the new feature but it doesn't help me with the use case I mentioned.
To be clearer, I will describe an example use case:

1. A project starts with the following directory structure:
    ```
    src
    +-- myclass.ts
    +-- index.ts
    ```

2. I add a _data_ directory in the _src_ directory, with the _index.ts_ and _mydata.ts_ files in it:
    ```
    src
    +-- data
   |  +-- mydata.ts
   |  +-- index.ts
    +-- myclass.ts
    +-- index.ts
    ```

3. At this point, I'd like 2 barrel files to be automatically updated:
    1. _src/data/index.ts_ should export the _src/data/mydata.ts_ module:
      ```export * from './mydata';```
    2. _src/index.ts_ should export the _src/data/index.ts module
      ```export * from './data';```

    Instead, what actually happens with version 1.4.0 is that the _src/data/mydata.ts_ module is exported by the _src/index.ts_ barrel.

**Comment by testpossessed** [comment]
Understood, effectively having a higher level barrel export a lover level barrel.  Will look into that next.

Mike

Kind Regards
Mike Hanson



On Thu, Mar 21, 2019 at 2:38 PM +0000, "Marco Labarile" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tried the new feature but it doesn't help me with the use case I mentioned.
To be clearer, I will describe an example use case:

  1.  A project starts with the following directory structure:

src
+-- myclass.ts
+-- index.ts


  2.  I add a data directory in the src directory, with the index.ts and mydata.ts files in it:

src
+-- data
|  +-- mydata.ts
|  +-- index.ts
+-- myclass.ts
+-- index.ts


  3.  At this point, I'd like 2 barrel files to be automatically updated:

     *   src/data/index.ts should export the src/data/mydata.ts module:
export * from './mydata';
     *   src/index.ts should export the _src/data/index.ts module
export * from './data';

Instead, what actually happens with version 1.4.0 is that the src/data/mydata.ts module is exported by the src/index.ts barrel.

**Comment by testpossessed** [comment]
Just to let you know I am working on this.  I am effectively re-writing the extension using TDD to make it unit testable.

What started out as a simple extension, created mainly for my own use, has turned into something that needs to be more professionally implemented so fixing that now.

I hope to finish it by the end of this week.

**Comment by labarilem** [comment]
Hi,
just wanted to let you know I can help if you need some code for this issue 😄

**Comment by testpossessed** [comment]
I am just about there.  I decided to do a lot of re-factoring to make the components more testable and it took longer than expected.  I am also trying to introduce some integration tests, but the limitations of the extension host  during testing make that near impossible, there seems to be no way to automate something as simple as selecting a folder in the explorer so you can execute a command against it.

**Comment by testpossessed** [comment]
@labarilem 
I have finished coding this change, manually testing it seems to do as you requested.  You have to have Recursive Barrelling Enabled.  I am keen to do a bit more testing before publishing, would you be up for doing a bit of testing, either by cloning the repo and running the the extension in debug more or receiving a package from that you can install manually?

**Comment by labarilem** [comment]
@testpossessed sure, how can I run it in debug mode?

**Comment by testpossessed** [comment]
I actually went ahead and published v1.5 this morning, so you should be able to update and test

Kind Regards
Mike Hanson



On Sat, Jun 15, 2019 at 8:04 PM +0100, "Marco Labarile" <notifications@github.com<mailto:notifications@github.com>> wrote:


@testpossessed<https://github.com/testpossessed> sure, how can I run it in debug mode?

**Comment by labarilem** [comment]
I think there might be an issue.

With this file structure:

```
data
+-- file
|  +-- file.ts
|  +-- index.ts
+-- mydata.ts
```

Expected `data/index.ts` to be generated:
```
export * from './mydata';
export * from './file';
```

Actual `data/index.ts` that is generated:
```
export * from './mydata';
export * from './file/file';
export * from './file';
```

**Comment by testpossessed** [comment]
Hmm,

That is strange, that is exactly the scenario I tested many times while developing it and it seemed to be producing exactly as you expect.

I will look into it more this week.

Mike

**Comment by testpossessed** [comment]
So I found the issue, the code was inadvertently dependent on the alphabetical order of file names.  I just applied a fix and published v1.5.1 please test and let me know of any more issues.  I did some cursory testing of my own but have another commitment now, but will test more myself later this week.

**Comment by labarilem** [comment]
Now when I right-click on a folder and pick the `Create barrel` menu option, no barrel file is ever generated. I've tried reinstalling the extension, realoading the vscode window, etc., but the issue persists.

**Comment by testpossessed** [comment]
Apologies for this, the issue may be related to bundling, the refactoring generated many more files and I got warnings with a recommendation to bundle using WebPack, I followed the guide and it appeared to work in my testing.  I will try some testing in a clean environment to see what went wrong.

**Comment by testpossessed** [comment]
I have reverted the bundling changes and published v1.5.2.  I will tackle bundling separately next.  Again apologies for breaking it.

**Comment by testpossessed** [comment]
That still doesn't appear to be working after installing, investigating further

**Comment by testpossessed** [comment]
Ok, I forgot to revert .vscodeignore along with package.json. v1.5.3 is working as expected

**Comment by labarilem** [comment]
Okay, working as expected for me too :smile:

**Comment by testpossessed** [comment]
Great news.
