### ISSUE TITLE
Support overwriting barrel

### ISSUE THREAD

**Issue by snebjorn** [testpossessed/auto-barrel#4]
It would be handy that Auto Barrel would just overwrite the index.ts file if a barrel already exist instead of giving a warning.

The reason is that most of the time I just create the new files, forgetting to turn on Auto Barrel. Once the files have been created turning on Auto Barrel doesn't trigger an update. So I have to delete the barrel and re-create it. It's an unnecessary inconvenience to an otherwise awesome extension :)

**Comment by testpossessed** [comment]
Could you provide some steps to replicate this problem as I am struggling to understand and replicate the issue.

I know the Create Barrel command from the menu does this check, but running the Auto Barrel command from command pallete shouldn't create this warning as it just monitors changes to files it doesn't actually try to create any files.

Some idea of your folder/file structure would help too.

**Comment by snebjorn** [comment]
Ah sorry, perhaps I should have made it clear that it's when using the "Create Barrel" option

![image](https://user-images.githubusercontent.com/1266245/64173737-36012780-ce58-11e9-843f-7531846163e7.png)

**Comment by testpossessed** [comment]
Thanks for the clarification.  I think I would rather provide an Update Barrel option rather than change the existing command to overwrite.

I will get on that this evening when I am done with work

**Comment by testpossessed** [comment]
I have just published an update that adds an Update Barrel command to the context menu when you right click on a barrel file.  Please try it out and let me know if you have any issues.

**Comment by snebjorn** [comment]
Hmm after the update the Auto Barrel doesn't seem to work. It doesn't create a new barrel when no index.ts file is present.
Not sure if I messed something up.

**Comment by testpossessed** [comment]
Sorry about that, I will take a look and fix as soon as I am done at work.  It seemed to be working fine before I deployed.

I keep trying to implement the recommended practice of bundling with webpack to help speed up loading but it has failed twice now and I have to roll it back, hence the v1.6.1 rather than just 1.6.0

**Comment by snebjorn** [comment]
My buddy was using VSCode 1.37.1 is worked, then he updated VSCode to 1.38.0 and then it stopped working

**Comment by testpossessed** [comment]
That is good to know, will look into that too.  I am on 1.38.0

**Comment by testpossessed** [comment]
I have just released an update to v1.6.2 that hopefully fixes the problem.

I found the Update Barrel command was working intermittently and it finally found it failed when the barrel file was active or open with pending changes.  I was trying to overwrite the file but that seemed to be the problem.  I now replace the contents and that seems to work in all cases.

This fix seems to somehow made Create Command work consistently too.

Please try it out and let me know how you get on.

**Comment by snebjorn** [comment]
When I run right-click "Create Barrel" or "Update Barrel" nothing happens. No error, no file created or updated.

When I run Create Barrel from the command pallet I get this error
> command 'autoBarrel.createBarrel' not found

And Update Barrel
> command 'autoBarrel.updateBarrel' not found

Auto Barrel - start
> command 'autoBarrel.start' not found

The extension is installed :/

**Comment by testpossessed** [comment]
Sorry about all the issues, this is very strange.  I didn't get the chance to install the update and test last night as I have family visiting, but it ran perfectly when debugging so expected it should work.  Hopefully you are able to install a previous version i.e. 1.5.* until I can resolve this properly.

**Comment by snebjorn** [comment]
No worries. I'll try an earlier version :)

**Comment by testpossessed** [comment]
Finally solved the problem, some left over config from attempt to package with webpack.  Update to v1.6.5 and all should be good.  Not the extension now requires VS Code 1.38.*

Please let me know if you have any issues.

**Comment by snebjorn** [comment]
It works! Thank you for adding this feature ❤️
