### ISSUE TITLE
"Create barrel" command not working

### ISSUE THREAD

**Issue by labarilem** [testpossessed/auto-barrel#5]
Hi,

the "Create barrel" command, available in the file explorer context menu when right-clicking on a folder, is no longer working.
When I click on it, nothing happens.

**Comment by testpossessed** [comment]
Please install an earlier version before 1.6.0 i.e. 1.5.*.

Between the change for #4 and the update to VS Code 1.38 something is not working once packaged and published even though it works perfectly in debug mode

**Comment by testpossessed** [comment]
v1.6.5 is working now, however requires latest stable version of VS Code 1.38.*.

Please check and let me know if you have any issues.

**Comment by labarilem** [comment]
Ok, now the command is working as expected. 
Thanks 😄

**Comment by labarilem** [comment]
Ok, now the command is working as expected. 
Thanks 😄

**Comment by Morriz** [comment]
The create command is not even visible anymore.

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
