### ISSUE TITLE
Missing "out" folder in extension since 1.6.1

### ISSUE THREAD

**Issue by gaspard** [testpossessed/auto-barrel#6]
The installed folder does not contain an "out" folder but the `package.json` file mentions this as "main":

```json
  "main": "./out/extension.js",
```

![image](https://user-images.githubusercontent.com/21707/67929996-06a03a00-fbbf-11e9-99cf-fecafc4c160d.png)

## 1.6.0 has the file but does not work...

1.5.8 works fine.

**Comment by testpossessed** [comment]
Hi, sorry about the issue.

v1.6.5 is the latest version but it requires VS Code 1.38.*

I will look into removing those old versions

**Comment by gaspard** [comment]
Ah, thanks for the incredibly fast response !!

All good then (I created `repo-cooker` for npm releases and know how much all this "just publish my stuff" thing can be hard to get right).

Thanks for the great extension !!

PS: I just upgraded vscode and the latest version works fine 😊

**Comment by testpossessed** [comment]
Great news, glad you like it.
