### ISSUE TITLE
Support .vue files

### ISSUE THREAD

**Issue by Emobe** [testpossessed/auto-barrel#7]
Would be nice if we could look for .vue files, which are just exported modules. Happy to provide a PR if this idea is welcomed.

**Comment by testpossessed** [comment]
It shouldn't take much to enable that.  It would need to include updating the setting for default language to include Vue and perhaps the default value for Search Glob setting to include .vue.

If you prefer to go down the PR route that works for me, I have time to get it done between now and Monday.  Your choice.

**Comment by Emobe** [comment]
Oh if you wouldn't mind getting it done, I'd really appreciate it as I'm kinda tied up at the moment. :(

**Comment by testpossessed** [comment]
On it

**Comment by testpossessed** [comment]
Just to be clear, is the barrel file a .vue file as well?

**Comment by Emobe** [comment]
Nope, the barrel should be a .js file still. I'd just like .vue files to be included within the barrel.

**Comment by testpossessed** [comment]
Never used Vue.js so need to ask, do I need to include the .vue extension in the import statement, or is there some special behaviour that takes care of that.

**Comment by testpossessed** [comment]
I have just published v1.7.0 please try this out and let me know if you have any issues

**Comment by Emobe** [comment]
Sorry for the late reply. I've just got round to checking it, just a quick change is needed

No the `.vue` extension is not needed, they're just exported .js modules so the extension is resolved by webpack.

Currently it creates it like this
`export { default as MFormFilter.vue } from './MFormFilter.vue';`

This won't work for the project because the file I want to export is actually at `./MFormFilter/index.vue`

If you could make it like below, that'd be great thanks
`export { default as MFormFilter } from './MFormFilter';`

**Comment by testpossessed** [comment]
Ok, will look at it later today and fix

**Comment by testpossessed** [comment]
Published v1.7.1 that should be what you requested.  As always let me know if you have any issues

**Comment by Emobe** [comment]
Apologies, I have been busy with work and then it was christmas. I will be testing this today.

**Comment by Emobe** [comment]
Works great for me. Thanks a lot!

**Comment by testpossessed** [comment]
Great news.
