### ISSUE TITLE
Exports are sorted randomly

### ISSUE THREAD

**Issue by alexsherekin** [testpossessed/auto-barrel#9]
Sorting of exports in the resulting file is strange. It would be nice to have them sorted by path

**Comment by testpossessed** [comment]
The extension doesn't do any explicit sorting.  When the create or update barrel commands are used the exports are added in the order they are provided by the VS Code file system provider.  There after if auto barelling is started it will append new exports to the end.

I know the default tslint rules require exports to be in a specific order but I don't think it should be the responsibility of the extension to maintain the order.

**Comment by snebjorn** [comment]
@testpossessed perhaps an option to run formatting on the file after create/update. That would solve it and keep the projects sorting style.

**Comment by testpossessed** [comment]
I will look into that

**Comment by testpossessed** [comment]
Sorry folks I am not going to do anything about this one.

As mentioned I don't think it should be the responsibility of this extension to set the order of exports.  The additional overhead of sorting on the create and update barrel commands affects performance too much for my liking.  Similarly the performance of the Auto Barrel feature is affected too much by making it sort the exports.

I looked at the option to run the format command but this clashed with my own settings where I have VS Code setup to format on save automatically so I am going to leave things as is and let individuals take care of sorting if required.

Personally I don't see it as a hardship to fix the ordering as part of my final prep for a pull request or push when running tslint.
